language: node_js
node_js:
  - "node"
branches:
  only:
    - master
install:
  - npm install
  - npm install -g firebase-tools
after_success:
  - npm run build-prod
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive